---
title: "LDATS changepoint"
author: "Renata Diaz"
date: "1/8/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(LDATS)
```

## LDATS LDA

### Setup
To run changepoint models: 
```{r setup ldats lda + ldats cpt, eval = T}
#### Data #### 

data(rodents)

ldats_dat <- rodents[[1]]
ldats_dates <- rodents[[2]]
head(ldats_dat)
source('christensen-ecology-files/rodent_data_for_LDA.r')
dat = create_rodent_table(period_first = 1,
                          period_last = 436,
                          selected_plots = c(2,4,8,11,12,14,17,22),
                          selected_species = c('BA','DM','DO','DS','NA','OL','OT','PB','PE','PF','PH','PI','PL','PM','PP','RF','RM','RO','SF','SH','SO'), diagnose = F)

# dates to go with count data
moondat = read.csv(text=getURL("https://raw.githubusercontent.com/weecology/PortalData/master/Rodents/moon_dates.csv"),stringsAsFactors = F)
moondat$date = as.Date(moondat$censusdate)

period_dates = filter(moondat,period %in% rownames(dat)) %>% select(newmoonnumber, period,date)
dates = period_dates$date

ch_dat <- dat

ch_dates <- dates
ch_newmoons <- period_dates$newmoonnumber

rm(list = c('dat', 'dates',
            'create_rodent_table'))

ldats_dat <- as.matrix(ch_dat)
ldats_dat <- apply(ldats_dat, c(1,2), FUN = as.integer)
rodents$document_term_table <- ldats_dat
rm(ldats_dat)
rm(ldats_dates)
rm(ch_dat)

#### Load LDA ####
load('/Users/renatadiaz/Documents/model-stash/ldats_lda.Rds')
year_continuous = 1970 + as.integer(julian(ch_dates)) / 365.25
x = data.frame(
  year_continuous = year_continuous,
  sin_year = sin(year_continuous * 2 * pi),
  cos_year = cos(year_continuous * 2 * pi)
)

x$newmoon <- ch_newmoons
x <- select(x, newmoon, sin_year, cos_year)
```


### Run the TS models
```{r run ldats lda + ldats cpt, eval = F}
#### Run LDATS changepoint ####

ldats_ldats_cpt <- TS_on_LDA(LDA_models = ldats_lda_selected, 
                             document_covariate_table = x,
                             formulas = ~ sin_year + cos_year,
                             nchangepoints = 1:6,
                             weights = NULL)


save(ldats_ldats_cpt, file = '/Users/renatadiaz/Documents/model-stash/ldats_lda_ldats_cpt.Rds')
rm(ldats_ldats_cpt)
rm(ldats_lda_selected)
```

```{r load ldats lda + ldats cpt results, echo = F}
load('/Users/renatadiaz/Documents/model-stash/ldats_lda_ldats_cpt.Rds')
```

### Select model

```{r select ldats lda + ldats cpt}

ldats_ldats_cpt_selected <- select_TS(ldats_ldats_cpt)
```

### Show results

```{r show ldats lda + ldats cpt}
plot(ldats_ldats_cpt_selected)
ldats_ldats_cpt_selected$formula
ldats_ldats_cpt_selected$nchangepoints
cpt_means <- ldats_ldats_cpt_selected$rho_summary$Mean

cpt_means <- floor(cpt_means)
cpt_means <- as.data.frame(cpt_means)
colnames(cpt_means) <- 'newmoonnumber'
cpt_means$cpt <- 1:ldats_ldats_cpt_selected$nchangepoints

cpt_dates <- as.data.frame(moondat) %>%
  dplyr::select(newmoonnumber, newmoondate) %>%
  dplyr::left_join(cpt_means, by = 'newmoonnumber') %>%
  dplyr::filter(!is.na(cpt))

cpt_dates

write.csv(cpt_dates, 'ldats_ldats_dates.csv')

```

```{r clean up ldats lda + ldats cpt, echo = F}
rm(ldats_ldats_cpt)
rm(ldats_ldats_cpt_selected)
rm(ldats_lda_selected)

```


## Paper LDA

### Load LDA
```{r load paper LDA}
#### Load paper LDA ####
load('/Users/renatadiaz/Documents/model-stash/paper_lda.Rds')
```

### Run TS models 

```{r run paper LDA + ldats cpt, eval = F}
paper_ldats_cpt <- TS_on_LDA(LDA_models = ldamodel, document_covariate_table = x, formulas = ~ sin_year + cos_year,nchangepoints = 1:6, weights = NULL)
save(paper_ldats_cpt, file = '/Users/renatadiaz/Documents/model-stash/paper_lda_ldats_cpt.Rds')
```

```{r load paper LDA + ldats cpt, echo = F}
load('/Users/renatadiaz/Documents/model-stash/paper_lda_ldats_cpt.Rds')
```

```{r select paper lda + ldats cpt}
paper_ldats_cpt_selected <- select_TS(paper_ldats_cpt)
```

### Show results

```{r show paper lda + ldats cpt}
plot(paper_ldats_cpt_selected)
paper_ldats_cpt_selected$formula
paper_ldats_cpt_selected$nchangepoints
cpt_means <- paper_ldats_cpt_selected$rho_summary$Mean


cpt_means <- floor(cpt_means)
cpt_means <- as.data.frame(cpt_means)
colnames(cpt_means) <- 'newmoonnumber'
cpt_means$cpt <- 1:paper_ldats_cpt_selected$nchangepoints

cpt_dates <- as.data.frame(moondat) %>%
  dplyr::select(newmoonnumber, newmoondate) %>%
  dplyr::left_join(cpt_means, by = 'newmoonnumber') %>%
  dplyr::filter(!is.na(cpt))

cpt_dates

write.csv(cpt_dates, 'paper_ldats_dates.csv')

```

