#' @title Conduct a single Time Series analyses on a set of LDA models
#'
#' @description This is the main Time Series analyses function.
#'
#' @param data Class \code{data.frame} object including [1] the time variable
#'   (indicated in \code{control}), [2] the predictor variables (required by
#'   \code{formula}) and [3], the multinomial response variable (indicated
#'   in \code{formula}). Note that the response variables should be formatted
#'   as \code{<name>.1}, \code{<name>.2}, etc. (where \code{<name>} is the
#'   actual name of the response variable, such as \code{gamma} for a standard
#'   TS analysis of LDA output. 
#'
#' @param formula \code{formula} describing the continuous change. Any 
#'   predictor variable included must also be a column in the
#'   \code{data}.  Any (multinomial) response variable must also be a set of
#'   columns in \code{data}. 
#'
#' @param nchangepoints Integer corresponding to the number of 
#'   change points to include in the model. 0 is a valid input (corresponding
#'   to no change points, so a singular time series model), and the current 
#'   implementation can reasonably include up to 6 change points. The 
#'   number of change points is used to dictate the segementation of the data  
#'   for each continuous model and each LDA model.
#'
#' @param weights Optional class \code{numeric} vector of weights for each 
#'   document. Corresponds to the vector \strong{\eqn{v}} in the math 
#'   description.
#'
#' @param control Class \code{TS_controls} list, holding control parameters
#'   for the Time Series model including the parallel tempering Markov Chain 
#'   Monte Carlo (ptMCMC) controls, generated by 
#'   \code{\link{TS_controls_list}}.
#'
#' @return the set of results from TS
#'
#' @export
#'
TS <- function(data, formula, nchangepoints, weights, 
               control = TS_controls_list()){

  check_timename(data, control$timename)
  check_formula(formula, data)

  TS_memo <- memoise_fun(multinom_TS, control$memoise)





}

#' @title Verify that a formula is proper
#' 
#' @description Verify that the formula is actually a formula and that the
#'   response and predictor variabless are all included in the data.
#'   
#' @param formula Formula to evaluate.
#'
#' @param data Class \code{data.frame} object including [1] the time variable
#'   (indicated in \code{control}), [2] the predictor variables (required by
#'   \code{formula}) and [3], the multinomial response variable (indicated
#'   in \code{control}).
#'
#' @return Nothing.
#' 
#' @export
#'
check_formula <- function(formula, data){

  if (!is(formula, "formula")){
    stop("formula does not contain a single formula")
  }

  respLoc <- attr(terms(formula), "response")
  if (respLoc == 0){
    stop("formula inputs should include response variable")
  }  

  resp <- as.character(attr(terms(formula), "variables"))[-1][respLoc]
  pred <- attr(terms(formula), "term.labels")
  if (!resp %in% colnames(data)){
    stop("formula includes response not present in data")
  }
  if (!all(pred %in% colnames(data))){
    misses <- pred[which(pred %in% colnames(data) == FALSE)]
    mis <- paste(misses, collapse = ", ")
    stop(paste0("formula includes predictors not present in data: ", mis))
  }
}


#' @title Create the controls list for the Time Series model
#'
#' @description This function provides a simple creation and definition of a
#'   list used to control the time series model fit occurring within 
#'   \code{\link{TS}}. 
#'
#' @param memoise Logical indicator of whether the multinomial functions 
#'   should be memoised (via \code{\link[memoise]{memoise}}). Memoisation 
#'   happens to both \code{\link{multinom_TS}} and 
#'   \code{\link{multinom_TS_chunk}}.
#'
#' @param response Character indicating the response variable used in the time
#'   series. 
#'
#' @param timename Character indicating the time variable used in the time 
#'   series. 
#'
#' @return List of class \code{TS_controls}.
#'
#' @export
#'
TS_controls_list <- function(memoise = TRUE, response = "gamma", 
                             timename = "newmoon"){
  out <- list(memoise = memoise, response = response, timename = timename)
  class(out) <- c("TS_controls", "list")
  out
}

#' @title Logical control on whether or not to memoise
#'
#' @description This function provides a simple, logical toggle control on
#'   whether the function \code{fun} should be memoised via
#'   \code{\link[memoise]{memoise}} or not. 
#'
#' @param fun Function name to (potentially) be memoised.
#'
#' @param memoise_fun Logical value indicatiing if \code{fun} should be 
#'   memoised.
#'
#' @return \code{fun}, memoised if desired.
#'
#' @export
#'
memoise_fun <- function(fun, memoise_fun){
  if (memoise_fun){
    fun <- memoise(fun)
  }
  fun
}